language: node_js

node_js:
  - "10"

cache:
  directories:
    - node_modules

notifications:
  email: false

jobs:
  include:
    - stage: build
      script: yarn build
    - stage: unit test
      script: yarn test
    - stage: end-to-end test
      script: ./cypress.sh
