language: csharp

dotnet: 1.0.1

cache:
  directories:
    - node_modules

notifications:
  email: false

jobs:
  include:
    - stage: build
      script: ./build.sh
    - stage: unit test
      script: ./rps-c#/xunit.sh
    - stage: end-to-end test
      script: ./rps/cypress.sh
