language: csharp

dotnet: 1.0.1
mono: none
install:
  - dotnet restore
  - nvm install 10.0.0
  - nvm use 10.0.0

cache:
  directories:
    - node_modules

notifications:
  email: false

jobs:
  include:
    - stage: build
      script: ./build.sh
    - stage: unit test
      script: ./rps-c#/xunit.sh
    - stage: end-to-end test
      script: ./rps/cypress.sh
