language: node_js

node_js:
  - "10"

cache:
  directories:
    - node_modules

notifications:
  email: false

jobs:
  include:
    - stage: build
      script: cd rps && yarn build
    - stage: unit test
      script: ./rps-c#/xunit.sh
    - stage: end-to-end test
      script: ./rps/cypress.sh
