---
resources:
- name: rock-paper-scissors
  type: git
  source:
    uri: https://github.com/safiranugroho/rock-paper-scissors.git

jobs:
- name: back-end
  public: true
  plan:
  - get: rock-paper-scissors
    trigger: true
  - task: build back-end
    file: rock-paper-scissors/ci/dotnet.yml
- name: front-end
  public: true
  plan:
  - get: rock-paper-scissors
    trigger: true
  - task: build front-end
    file: rock-paper-scissors/ci/node.yml